blueprints/stock.py
from flask import Blueprint, render_template
import requests

stock = Blueprint('stock',__name__, url_prefix='/stock')

#https://financialmodelingprep.com/api/v3/stock/real-time-price/AAPL?apikey=demo

API_URL = 'https://financialmodelingprep.com/api/v3/stock/real-time-price/{ticker}'

def fetch_price(ticker):
    data=requests.get(API_URL.format(ticker=ticker.upper()), params={'apikey': 'demo'}).json()
    return data['price']

def fetch_income(ticker):
    # https://financialmodelingprep.com/api/v3/financials/income-statement/AAPL?apikey=demo&period=quarter
    url = 'https://financialmodelingprep.com/api/v3/financials/income-statement/{}'.format(ticker)
    financials =requests.get(url, params={'period': 'quarter', 'apikey': 'demo'}).json()['financials']
    financials.sort(key=lambda quarter: quarter["date"])
    return financials

@stock.route('/<ticker>')
def quote(ticker):
    price = fetch_price(ticker)
    return render_template('stock/quote.html',ticker=ticker, ticker_price=price)

@stock.route('/<string:ticker>/financials')
def financials(ticker):
    data= fetch_income(ticker)
    return render_template('stock/financials.html', ticker=ticker, financials=data)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}| Stock App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between foxv-main-color">
    <a class="navbar-brand" href="{{ url_for('index') }}">Stock App</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{{ url_for('index') }}" class="nav-link">Home</a></li>
        </ul>
    </div>
</nav>
    <div class="container-fluid">
        <div class="row">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>
</html>

templates/home/index.html
{% extends 'base.html' %}

{% block title %}Home {{ ticker_price}}{% endblock title %}
{% block content %}
    <div class="col-sm">
        <h1>Welcome to Stock Application</h1>
        <hr/>
        <h2></h2>
    </div>
    <div class="col">
        {% include 'shared/portfolio.html' %}
    </div>
{% endblock content %}

templates/macros.html
    {% macro stock_quote_link(stock_ticker) %}
        <a href="{{ url_for('stock.quote', ticker=stock_ticker) }}"> {{ stock_ticker | upper }}</a>
    {% endmacro  %}

templates/shared/portfolio.html
{% from "macros.html" import stock_quote_link %}
<h2>Stock portfolio</h2>
<ul class="">
    {% for ticker in ['aapl', 'fb', 'googl', 'tsla'] %}
        <li>View {{ stock_quote_link(ticker) }}</li>
    {% endfor %}
</ul>

templates/stock/financials.html
{% extends 'base.html' %}
{% block title %}{{ticker}} | Financials{% endblock title %}
{% block content %}

{% endblock content %}

templates/stock/quote.html
{% extends 'base.html' %}

{% block title %}{{ ticker }} {{ ticker_price}}{% endblock title %}
{% block content %}
    <div class="col-sm">
        <h1 class="mb-3">{{ ticker | upper }}</h1>
        <hr>
        <h2>Price: ${{ ticker_price | round(4, 'floor') }}</h2>
    </div>
    <div class="col">
        {% include 'shared/portfolio.html' %}
    </div>
{% endblock content %}